### ISSUE TITLE
View image in admin mode when editing event

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/front_end_infinite#23]
Unable to view and change image in admin mode when editing event

**Comment by MatthewGidcomb** [comment]
[Commit 9022f041](https://github.com/infinite-industries/front_end_infinite/commit/9022f041f7017850c6bca7f4b913e8eef5e9d685) shows the main and social media optimized images on the admin form, but the server isn't set up to support uploads on event edit yet.

**Comment by Digi-D** [comment]
We can see it but can't change it!
