### ISSUE TITLE
WhoWeAre page needs to be completed

### ISSUE THREAD

**Issue by MatthewGidcomb** [infinite-industries/front_end_infinite#31]
I think this is the only static page that is incomplete.

- [x] Bio for Chris
- [x] Bio for Evan
- [x] Bio for Ryan (or remove)
- [x] Bio for board members
- [x] Name and link for Kasey's company

The final acknowledgements section may also need reorganizing.

**Comment by Digi-D** [comment]
Board Members commented out for now.

**Comment by Digi-D** [comment]
Kasey's company link taken out
