### ISSUE TITLE
Create Integration Test For Checking Nav Against Admin

### ISSUE THREAD

**Issue by chriswininger** [infinite-industries/front_end_infinite#6]
1. Test that checks that non-authenticated user does not see links that require authentication and can't navigate to them

**Comment by chriswininger** [comment]
yep good idea

**Comment by chriswininger** [comment]
also that it can't hit those routes on the portal back end. The client will keep them from viewing the page (nav is all client side), but it's the server that has to reject the post reuests

**Comment by MatthewGidcomb** [comment]
This was written during the Nuxt refactor in response to the everyone-sees-the-admin-link-when-an-admin-is-logged-in issue.
